import type { LeadType, MenuItem } from "@/app/types";

export const WHATSAPP_NUMBER = "+447961880693";
export const WAITLIST_STORAGE_KEY = "ufoBurgerWaitlist";
export const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i;

export const LEAD_TYPE_OPTIONS = new Set<LeadType>([
  "Customer",
  "Investor",
  "Partner",
  "Other",
]);

export const MENU_ITEMS: MenuItem[] = [
  {
    id: "mercury",
    name: "Mercury",
    category: "savory",
    type: "Savory Burger",
    tag: "Spicy, hot, sharp",
    detail: "Beef, jalapeno, chili sauce, lime, smoked paprika.",
    image: "/planets/mercury.PNG",
    planetClass: "menu-feature--mercury",
  },
  {
    id: "venus",
    name: "Venus",
    category: "savory",
    type: "Savory Burger",
    tag: "Creamy, soft, stretchy",
    detail: "Chicken, melted cheese, cream sauce, a hint of honey.",
    image: "/planets/venus.PNG",
  },
  {
    id: "earth",
    name: "Earth",
    category: "savory",
    type: "Savory Burger",
    tag: "Classic, balanced, fresh",
    detail: "Beef, lettuce, tomato, pickles, house sauce.",
    image: "/planets/earth.PNG",
  },
  {
    id: "mars",
    name: "Mars",
    category: "savory",
    type: "Savory Burger",
    tag: "Spicy, smoky, meaty",
    detail: "Lamb, roasted pepper, paprika, yogurt-garlic sauce.",
    image: "/planets/mars.PNG",
  },
  {
    id: "jupiter",
    name: "Jupiter",
    category: "savory",
    type: "Savory Burger",
    tag: "Big, bold, layered",
    detail: "Double beef, cheddar, bacon, onion, BBQ.",
    image: "/planets/jupiter.png",
  },
  {
    id: "saturn",
    name: "Saturn",
    category: "savory",
    type: "Savory Burger",
    tag: "Balanced, BBQ-forward",
    detail: "Beef, onion rings, BBQ sauce, cheddar.",
    image: "/planets/saturn.PNG",
    planetClass: "menu-feature--saturn",
  },
  {
    id: "neptune",
    name: "Neptune",
    category: "savory",
    type: "Savory Burger",
    tag: "Cool and refreshing",
    detail: "Fish or chicken, yogurt sauce, mint, lime.",
    image: "/planets/neptune.PNG",
    planetClass: "menu-feature--neptune",
  },
  {
    id: "pluto",
    name: "Pluto",
    category: "savory",
    type: "Savory Burger",
    tag: "Deep, mysterious, sweet-salty",
    detail: "Beef, black garlic sauce, sesame.",
    image: "/planets/pluto.PNG",
    planetClass: "menu-feature--pluto",
  },
  {
    id: "sirius",
    name: "Sirius",
    category: "savory",
    type: "Savory Burger",
    tag: "Rich, caramel-smoky",
    detail: "Premium beef, caramelized onion, BBQ sauce.",
    image: "/planets/sirius.PNG",
  },
  {
    id: "aurora",
    name: "Aurora",
    category: "sweet",
    type: "Sweet Line",
    tag: "Berry-cream, light",
    detail: "Soft bun, blueberry cream, lavender syrup.",
  },
  {
    id: "ice-comet",
    name: "Ice Comet",
    category: "sweet",
    type: "Sweet Line",
    tag: "Cold, minty, creamy",
    detail: "Ice cream, mint, white chocolate.",
  },
  {
    id: "dark-matter-sweet",
    name: "Dark Matter",
    category: "sweet",
    type: "Sweet Line",
    tag: "Chocolate, deep, sweet-salty",
    detail: "Chocolate ganache, sea salt, black bun.",
  },
  {
    id: "luna",
    name: "Luna",
    category: "sweet",
    type: "Sweet Line",
    tag: "Milky, delicate, creamy",
    detail: "White chocolate, coconut, cream.",
  },
  {
    id: "cosmic-cloud",
    name: "Cosmic Cloud",
    category: "sweet",
    type: "Sweet Line",
    tag: "Airy, vanilla",
    detail: "Whipped cream, meringue, vanilla.",
  },
  {
    id: "andromeda",
    name: "Andromeda Elixir",
    category: "drinks",
    type: "Deep Space - Essential Five",
    tag: "Crew Crafted",
    detail: "A deep violet berry drink lifted with fresh lime and a light cosmic sparkle.",
  },
  {
    id: "orion",
    name: "Orion Pulse",
    category: "drinks",
    type: "Deep Space - Essential Five",
    tag: "Blue citrus, mint, crushed ice",
    detail: "Bright blue citrus with cool mint and crushed ice - sharp, clean and refreshing.",
  },
  {
    id: "event-horizon",
    name: "Event Horizon",
    category: "drinks",
    type: "Deep Space - Essential Five",
    tag: "Black lime, ginger, bold",
    detail: "A smooth black lime and ginger blend with a bold, slightly spicy finish.",
  },
  {
    id: "dark-matter-drink",
    name: "Dark Matter",
    category: "drinks",
    type: "Deep Space - Essential Five",
    tag: "Blackberry, blackcurrant, rich",
    detail: "Blackberry and blackcurrant combined for a rich, dark and full-bodied flavour.",
  },
  {
    id: "polaris",
    name: "Polaris Ice",
    category: "drinks",
    type: "Deep Space - Essential Five",
    tag: "Sparkling citrus, fresh zest",
    detail: "Clear sparkling citrus with fresh zest - crisp, cold and effortlessly refined.",
  },
];

export const NAV_LINKS = [
  { href: "#legend", label: "Legend" },
  { href: "#menu", label: "Galaxy Menu" },
  { href: "#crew", label: "Crew" },
  { href: "#business", label: "Investors" },
] as const;
